# Jobs defined here use the idp/ci docker image from ECR by default. 
# Images are built via the identity-devops GitLab pipeline.

variables:

  ECR_REGISTRY: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com'

default:
  image: '${ECR_REGISTRY}/dashboard/ci:latest'

before_script:
  - gem install bundler 

.bundle_install: &bundle_install
  -  bundle install --retry=3 --path vendor/bundle
 
.build_cache:
  - &ruby_cache
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/bundle
    policy: pull

stages:
  - .pre
  - test
 
 
install_dependencies:
  stage: .pre
  cache:
    - <<: *ruby_cache
      policy: pull-push
  script:
    - *bundle_install
    - make setup

test_app:
  stage: test
  needs:
    - job: install_dependencies
  cache:
    - <<: *ruby_cache
  script:
    - *bundle_install
    - make test
  artifacts:
    paths:
      - /tmp/test-results
