# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: cimg/ruby:2.7

    working_directory: ~/identity-hostdata
    steps:
      - checkout

      - restore-cache:
          key: identity-hostdata-{{ checksum "identity-hostdata.gemspec" }}

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            make setup

      # Store bundle cache
      - save-cache:
          key: identity-hostdata-{{ checksum "identity-hostdata.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Tests
          command: |
            make test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
